%% ACAS Xu: ONNX → Native dlnetwork → INT8 Quantization → Simulink → C Code
% This script reproduces the full pipeline:
%   1. Import ONNX model (demonstrates custom layer issue)
%   2. Rebuild as native dlnetwork with extracted weights
%   3. Verify numerical equivalence
%   4. Quantize to INT8
%   5. Export to Simulink via exportNetworkToSimulink
%   6. Generate embedded C code via Embedded Coder

%% Phase 1: Attempt ONNX Import
fprintf('\n=== Phase 1: ONNX Import ===\n');
onnxFile = 'ACASXU_run2a_1_1_batch_2000.onnx';
onnxNet = importNetworkFromONNX(onnxFile);

fprintf('Imported network layers:\n');
for i = 1:numel(onnxNet.Layers)
    layerClass = class(onnxNet.Layers(i));
    fprintf('  Layer %d: %s (%s)\n', i, onnxNet.Layers(i).Name, layerClass);
    if contains(layerClass, 'Custom') || contains(layerClass, 'AutoGenerated') || contains(layerClass, 'nnet.onnx')
        fprintf('    *** CUSTOM/AUTOGENERATED — incompatible with quantization & Simulink ***\n');
    end
end

%% Phase 2: Rebuild as Native dlnetwork
fprintf('\n=== Phase 2: Rebuild Native dlnetwork ===\n');
onnxLayer = onnxNet.Layers(2);  % Fused MatMul_To_AddLayer1000

layers = [
    featureInputLayer(5, 'Name', 'input', 'Normalization', 'none')
    fullyConnectedLayer(50, 'Name', 'fc1')
    reluLayer('Name', 'relu1')
    fullyConnectedLayer(50, 'Name', 'fc2')
    reluLayer('Name', 'relu2')
    fullyConnectedLayer(50, 'Name', 'fc3')
    reluLayer('Name', 'relu3')
    fullyConnectedLayer(50, 'Name', 'fc4')
    reluLayer('Name', 'relu4')
    fullyConnectedLayer(50, 'Name', 'fc5')
    reluLayer('Name', 'relu5')
    fullyConnectedLayer(50, 'Name', 'fc6')
    reluLayer('Name', 'relu6')
    fullyConnectedLayer(5, 'Name', 'fc7')
];
nativeNet = dlnetwork(layers);

% Transfer weights from ONNX import
fcNames = {'fc1','fc2','fc3','fc4','fc5','fc6','fc7'};
wNames  = {'W0','W1','W2','W3','W4','W5','W6'};
bNames  = {'B0','B1','B2','B3','B4','B5','B6'};

for i = 1:7
    W = single(extractdata(onnxLayer.(wNames{i})));  % input_dim x output_dim
    B = single(extractdata(onnxLayer.Vars.(bNames{i})));
    nativeNet.Learnables{strcmp(nativeNet.Learnables.Layer, fcNames{i}) & ...
        strcmp(nativeNet.Learnables.Parameter, 'Weights'), 'Value'} = {dlarray(W')};
    nativeNet.Learnables{strcmp(nativeNet.Learnables.Layer, fcNames{i}) & ...
        strcmp(nativeNet.Learnables.Parameter, 'Bias'), 'Value'} = {dlarray(B)};
    fprintf('  %s: W=%s, B=%s\n', fcNames{i}, mat2str(size(W')), mat2str(size(B)));
end
fprintf('Native dlnetwork: %d layers, all single-precision\n', numel(nativeNet.Layers));

%% Phase 3: Verify Numerical Equivalence
fprintf('\n=== Phase 3: Numerical Verification ===\n');
rng(42);
X_raw = randn(5, 20);

% Manual forward pass using raw ONNX weights
Y_manual = zeros(5, 20);
for s = 1:20
    x = X_raw(:, s);
    h = double(extractdata(onnxLayer.W0))' * x + double(extractdata(onnxLayer.Vars.B0));
    h = max(h, 0);
    for layer = 2:6
        W = double(extractdata(onnxLayer.(wNames{layer})));
        B = double(extractdata(onnxLayer.Vars.(bNames{layer})));
        h = W' * h + B;
        h = max(h, 0);
    end
    W7 = double(extractdata(onnxLayer.W6));
    B7 = double(extractdata(onnxLayer.Vars.B6));
    Y_manual(:, s) = W7' * h + B7;
end

X_dl = dlarray(single(X_raw), 'CB');
Y_native = predict(nativeNet, X_dl);
Y_native_raw = double(extractdata(Y_native));

maxErr = max(abs(Y_manual - Y_native_raw), [], 'all');
cosine = dot(Y_manual(:), Y_native_raw(:)) / (norm(Y_manual(:)) * norm(Y_native_raw(:)));
fprintf('  Max absolute error: %.2e\n', maxErr);
fprintf('  Cosine similarity:  %.10f\n', cosine);

%% Phase 4: Codegen Compatibility Check
fprintf('\n=== Phase 4: Codegen Compatibility ===\n');
results = analyzeNetworkForCodegen(nativeNet);
fprintf('  Target "none": %s\n', string(results(1).Supported));
fprintf('  Target "arm-compute": %s\n', string(results(2).Supported));

%% Phase 5: INT8 Quantization
fprintf('\n=== Phase 5: INT8 Quantization ===\n');
qObj = dlquantizer(nativeNet, 'ExecutionEnvironment', 'MATLAB');

calibrationData = randn(1000, 5, 'single');
calDs = arrayDatastore(calibrationData, 'IterationDimension', 1);
calResults = calibrate(qObj, calDs);
fprintf('  Calibration entries: %d\n', height(calResults));

quantizedNet = quantize(qObj);
qDetails = quantizationDetails(quantizedNet);
fprintf('  IsQuantized: %d\n', qDetails.IsQuantized);
fprintf('  Quantized layers: %d\n', numel(qDetails.QuantizedLayerNames));

%% Phase 6: Export to Simulink
fprintf('\n=== Phase 6: Export to Simulink ===\n');
modelName = 'ACASXU_Simulink';
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if exist([modelName '.slx'], 'file')
    delete([modelName '.slx']);
end

exportNetworkToSimulink(quantizedNet, 'ModelName', modelName);
fprintf('  Simulink model created: %s.slx\n', modelName);

blocks = find_system(modelName, 'Type', 'Block');
fprintf('  Total blocks: %d\n', numel(blocks));

%% Phase 7: Generate C Code
fprintf('\n=== Phase 7: C Code Generation ===\n');
set_param(modelName, 'SystemTargetFile', 'ert.tlc');
set_param(modelName, 'SolverType', 'Fixed-step');
set_param(modelName, 'Solver', 'FixedStepDiscrete');
set_param(modelName, 'FixedStep', '0.01');
set_param(modelName, 'InstructionSetExtensions', 'None');
set_param(modelName, 'GenCodeOnly', 'on');
save_system(modelName);

slbuild(modelName);

codeDir = fullfile(pwd, [modelName '_ert_rtw']);
cFiles = dir(fullfile(codeDir, '*.c'));
hFiles = dir(fullfile(codeDir, '*.h'));
fprintf('  Generated: %d .c files, %d .h files\n', numel(cFiles), numel(hFiles));
for i = 1:numel(cFiles)
    fprintf('    %s (%d bytes)\n', cFiles(i).name, cFiles(i).bytes);
end

fprintf('\n=== Pipeline Complete ===\n');
fprintf('Quantized INT8 C code generated in: %s\n', codeDir);

% Save the network for later use
save('acasxu_native_net.mat', 'nativeNet');
save('acasxu_quantized_net.mat', 'quantizedNet');
